
server:
  port: ${LEARNING_ENGLISH_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: english
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/learning_english}
    #    url: ${DBMS_CONNECTION:jdbc:mysql://host.docker.internal:3306/learning_english}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
